// @ts-nocheck

import { Rolfis } from "@/components/rolfis";
import { resolveUrl } from "@/utils";
import Head from "next/head";
import { links } from "@/utils/data";
import { IFilters } from "@/types";
import { Profimann } from "@/components/profimann";
import { HeadRow } from "@/components/headRow";
import { Edobro } from "@/components/edobro";
import { Aquapure } from "@/components/aquapure";
import { Vodavdom } from "@/components/vodavdom";
import { Ukrakvateh } from "@/components/ukrakvateh";
import { Pershavoda } from "@/components/pershavoda";
import { Komfortvoda } from "@/components/komfortvoda";
import { Akvo } from "@/components/akvo";
import { Fons } from "@/components/fons";
import { Filterpoint } from "@/components/filterpoint";
import { Nemofilter } from "@/components/nemofilter";
import { Aqualife } from "@/components/aqualife";
import { Smartfilter } from "@/components/smartfilter";
import { Afilter } from "@/components/afilter";
import { Hydroeco } from "@/components/hydroeco";
import { Filter } from "@/components/filter";
import { Softis } from "@/components/softis";

export const getServerSideProps = async () => {
 let res = [];
 for (let link of links) {
  const { price, lastScraped } = await resolveUrl(link.link);
  res.push({
   link: link.link,
   title: link.name,
   website: link.website,
   price,
   normalPrice: link.normalPrice,
   lastScraped,
  });
 }

 return {
  props: {
   res,
  },
 };
};

export default function Home(props: { res: IFilters }) {
 return (
  <div className="text-md font-semibold p-2 text-slate-50">
   <Head>
    <title>Prices</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <HeadRow />
   <Rolfis data={props.res} />
   <Edobro data={props.res} />
   <Aquapure data={props.res} />
   <Vodavdom data={props.res} />
   <Ukrakvateh data={props.res} />
   <Pershavoda data={props.res} />
   <Komfortvoda data={props.res} />
   <Akvo data={props.res} />
   <Fons data={props.res} />
   <Filterpoint data={props.res} />
   <Nemofilter data={props.res} />
   <Aqualife data={props.res} />
   <Smartfilter data={props.res} />
   <Afilter data={props.res} />
   <Hydroeco data={props.res} />
   <Profimann data={props.res} />
   <Filter data={props.res} />
   <Softis data={props.res} />
  </div>
 );
}
