import Head from 'next/head'
import cheerio from 'cheerio'
import axios from 'axios'

export const getStaticProps = async () => {
  const { data } = await axios.get('https://profimann.com.ua/filtry-dlya-vody/filtry-mehanicheskoy-ochistki-vody/promyvnoy-filtr-honeywell-ff06-1-2aa-100-mkm-dlya-holodnoy-vody/')
  const $ = cheerio.load(data)
  const title = $('#tygh_main_container > section.content > div > div:nth-child(1) > section > div:nth-child(3) > div > div > h1').text()
  const price = $('#sec_discounted_price_3569').text();
  const lastScraped = new Date().toISOString()
  return {
    props: { title, price: price.slice(0, price.length/2), lastScraped },
    revalidate: 10,
  }
}

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-black'>{props.title}</div>
      <div>{props.price}</div>
    </>
  )
}
